### PR TITLE
Feat: implemented localization feature

### PR DESCRIPTION
**Pull request by chendjou237**

### CODE REVIEW

**Comment by chendjou237** [comment]
Some parts of the app may seem not be affected by the change in language due to the fact that there where out of the buildcontext and considered static strings by easy_localization package.

**Comment by yunweneric** [comment]
Hi @chendjou237 

Thank you so much for the amazing work you have done on the translation. I have a recommendation to make this much reusable and fine-grained

- I think your current implementation is so tied and dependent on EasyLocalization package. If we want to change to a different package in the future it will require us to go through the entire app to update that

Could we use this for the translation?


```dart
import 'package:easy_localization/easy_localization.dart';
import 'package:easy_localization/src/easy_localization_controller.dart';
import 'package:easy_localization/src/localization.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class LangUtil {
  

  static String trans(String? key, {Map<String, String>? args, BuildContext? context}) {
    if (key != '' && key != null) {
      String val = tr(key, namedArgs: args, context: context);
      return val;
    } else
      return '';
  }

  static bool isFrench(BuildContext context) {
    return context.deviceLocale.languageCode == 'fr';
  }
}

```


Usage 

```dart
 Text(
      LangUtil.trans("auth.forgot_password"),
      style: theme.textTheme.displayLarge,
  ),

```


This way if we want to change to another translation package, we will modify only the LangUtil.trans method. Please let me know what you think.

Also you should not worry  about going through your entire code to change it. You can use your editor's `Find and Replace` to quickly do this

**Comment by chendjou237** [comment]
Hello Yunweneric,

Thank you for your feedback and suggestions regarding the translation
implementation. I appreciate the recommendation to make the translation
logic more modular and adaptable to future changes. Your proposed approach
using the LangUtil class is indeed a great idea, and I am interested in
implementing this improvement. I will review the current codebase and
proceed with the necessary adjustments as per your suggestion. Please let
me know if there are any additional details or considerations I should keep
in mind while making these changes.

Best regards,
Chendjou Honore

**Comment by yunweneric** [comment]
Awesome @chendjou237 

Looking forward

**Comment by chendjou237** [comment]
Dear Yunweneric,

I hope this message finds you well. I wanted to inform you that I have
opened the pull request as per your request. I also want to apologize for
not pushing my changes the last time I worked on this; it was an oversight
on my part, and I appreciate your patience.

Best regards,
Chendjou Honore

**Pull request closed without merging**
